// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHGbHOFp19Ivk3zAz9qqBYDIH9cMuuMoQ',
    appId: '1:567672693811:web:0f1b4f3a78f8e7ed6baf46',
    messagingSenderId: '567672693811',
    projectId: 'mental-health-52b06',
    authDomain: 'mental-health-52b06.firebaseapp.com',
    storageBucket: 'mental-health-52b06.appspot.com',
    measurementId: 'G-MBVS6J4QBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQwKSbQb6rQN5fX4tgsn5tNyU2XTC2Ndg',
    appId: '1:567672693811:android:c95b604168f4ef0a6baf46',
    messagingSenderId: '567672693811',
    projectId: 'mental-health-52b06',
    storageBucket: 'mental-health-52b06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMi-3dMvNrilbCog7D6ilfC34yhJEInQ4',
    appId: '1:567672693811:ios:52003749d24033c56baf46',
    messagingSenderId: '567672693811',
    projectId: 'mental-health-52b06',
    storageBucket: 'mental-health-52b06.appspot.com',
    iosClientId: '567672693811-bktbvbcqlvn5cnnsg9i8vldokm3tqo6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.mhApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMi-3dMvNrilbCog7D6ilfC34yhJEInQ4',
    appId: '1:567672693811:ios:7452aedb8c296bb96baf46',
    messagingSenderId: '567672693811',
    projectId: 'mental-health-52b06',
    storageBucket: 'mental-health-52b06.appspot.com',
    iosClientId: '567672693811-ndi4pt1c335p9fuef4aq7v035u6p00g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mhApp.RunnerTests',
  );
}
